# Generated by Django 3.0.3 on 2020-09-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='country', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='cn', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='scriptwriter',
            field=models.CharField(default='编剧1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='政治', max_length=20),
            preserve_default=False,
        ),
    ]
