# Generated by Django 3.0.3 on 2020-09-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200908_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='introduction',
            field=models.CharField(default='简介测试', max_length=700),
            preserve_default=False,
        ),
    ]
