# Generated by Django 3.0.3 on 2020-09-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actortoactor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActorToActor',
        ),
    ]
