# Generated by Django 3.0.3 on 2020-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200908_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
