# Generated by Django 3.0.3 on 2020-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20200909_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthplace',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='actor',
            name='introduction',
            field=models.TextField(default='（暂无）'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='introduction',
            field=models.TextField(default='（暂无）'),
        ),
    ]
